/*
 * Rohan Rajesh, March 1, 2022
 * Multiple Choice Quiz
 * A cricket based multiple choice quiz
 */

/**
 *
 * @author roraj5945
 */
public class MultiChoiceQuiz extends javax.swing.JFrame {

    /**
     * Creates new form YES
     */
    public MultiChoiceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1BtnGroup = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblQ1 = new javax.swing.JLabel();
        lbQ2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        lblQ5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblScoreOutput = new javax.swing.JLabel();
        lblQ1A = new javax.swing.JLabel();
        lblQ1B = new javax.swing.JLabel();
        lblQ1C = new javax.swing.JLabel();
        lblQ1D = new javax.swing.JLabel();
        txtQ1Answer = new javax.swing.JTextField();
        txtQ2Answer = new javax.swing.JTextField();
        txtQ3Answer = new javax.swing.JTextField();
        txtQ4Answer = new javax.swing.JTextField();
        txtQ5Answer = new javax.swing.JTextField();
        lblQ2A = new javax.swing.JLabel();
        lblQ2B = new javax.swing.JLabel();
        lblQ2C = new javax.swing.JLabel();
        lblQ2D = new javax.swing.JLabel();
        lblQ3A = new javax.swing.JLabel();
        lblQ3B = new javax.swing.JLabel();
        lblQ3C = new javax.swing.JLabel();
        lblQ3D = new javax.swing.JLabel();
        lblQ4A = new javax.swing.JLabel();
        lblQ4B = new javax.swing.JLabel();
        lblQ4C = new javax.swing.JLabel();
        lblQ4D = new javax.swing.JLabel();
        lblQ5A = new javax.swing.JLabel();
        lblQ5B = new javax.swing.JLabel();
        lblQ5C = new javax.swing.JLabel();
        lblQ5D = new javax.swing.JLabel();
        lblQ1Out = new javax.swing.JLabel();
        lblQ2Out = new javax.swing.JLabel();
        lblQ3Out = new javax.swing.JLabel();
        lblQ4Out = new javax.swing.JLabel();
        lblQ5Out = new javax.swing.JLabel();
        lblScorePerc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblimg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitle.setText("Cricket Quiz");

        lblQ1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblQ1.setText("Q1: Who won the 2019 ODI CWC?");

        lbQ2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbQ2.setText("Q2: Who won the most recent IPL tournament?");

        lblQ3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblQ3.setText("Q3: From which country is the cricket bowler with the most wickets from?");

        lblQ4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblQ4.setText("Q4: From which country did/does the player with the most runs play for?");

        lblQ5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblQ5.setText("Q5: Who won the 2021 T20 CWC?");

        jButton1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("COMPLETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 24)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 0, 0));
        lblScore.setText("Your Score:");

        lblScoreOutput.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 24)); // NOI18N
        lblScoreOutput.setForeground(new java.awt.Color(255, 0, 0));

        lblQ1A.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ1A.setText("1. India");

        lblQ1B.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ1B.setText("2. Australia");

        lblQ1C.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ1C.setText("3. New Zealand");

        lblQ1D.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ1D.setText("4. England");

        txtQ1Answer.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtQ1Answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ1AnswerActionPerformed(evt);
            }
        });

        txtQ2Answer.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        txtQ3Answer.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtQ3Answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ3AnswerActionPerformed(evt);
            }
        });

        txtQ4Answer.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        txtQ5Answer.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        lblQ2A.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ2A.setText("1. CSK");

        lblQ2B.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ2B.setText("2. MI");

        lblQ2C.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ2C.setText("3. RCB");

        lblQ2D.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ2D.setText("4.SRH");

        lblQ3A.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ3A.setText("1. India");

        lblQ3B.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ3B.setText("2. Sri Lanka");

        lblQ3C.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ3C.setText("3. Scotland");

        lblQ3D.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ3D.setText("4. Australia");

        lblQ4A.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ4A.setText("1. Australia");

        lblQ4B.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ4B.setText("2. England");

        lblQ4C.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ4C.setText("3. India");

        lblQ4D.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ4D.setText("4. Ireland");

        lblQ5A.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ5A.setText("1. Pakistan");

        lblQ5B.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ5B.setText("2. India");

        lblQ5C.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ5C.setText("3. New Zealand");

        lblQ5D.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblQ5D.setText("4. Australia");

        lblQ1Out.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        lblQ2Out.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        lblQ3Out.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        lblQ4Out.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        lblQ5Out.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        lblScorePerc.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 24)); // NOI18N
        lblScorePerc.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nisha\\Pictures\\cricket.jpg")); // NOI18N

        lblimg2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nisha\\Pictures\\cricket2.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbQ2)
                                .addGap(18, 18, 18)
                                .addComponent(txtQ2Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblQ3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQ3Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(509, 509, 509)
                                        .addComponent(lblScore)
                                        .addGap(0, 0, 0)
                                        .addComponent(lblScoreOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblQ5)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtQ5Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(lblQ5Out, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(123, 123, 123)
                                                .addComponent(lblQ4Out, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(30, 30, 30)
                                .addComponent(lblScorePerc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQ5C)
                        .addGap(35, 35, 35)
                        .addComponent(lblQ5D)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblQ5A)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblQ3A)
                                        .addComponent(lblQ4A)
                                        .addComponent(lblQ2A)
                                        .addComponent(lblQ1A)))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblQ1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblQ1Out, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQ1Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(256, 256, 256))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblQ4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQ4Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(lblimg2)
                                .addGap(235, 235, 235)
                                .addComponent(lblTitle)
                                .addGap(187, 187, 187)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQ1B)
                                            .addComponent(lblQ2B))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQ2C)
                                            .addComponent(lblQ1C))
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblQ3B)
                                                    .addComponent(lblQ4B))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblQ4C)
                                                    .addComponent(lblQ3C))))
                                        .addGap(65, 65, 65)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQ4D)
                                    .addComponent(lblQ3D)
                                    .addComponent(lblQ1D)
                                    .addComponent(lblQ2D)))
                            .addComponent(lblQ5B))
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lblQ2Out, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(lblQ3Out, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblimg2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ1)
                    .addComponent(lblQ1A)
                    .addComponent(lblQ1B)
                    .addComponent(lblQ1C)
                    .addComponent(lblQ1D)
                    .addComponent(txtQ1Answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQ1Out, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ2A)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbQ2)
                                .addComponent(txtQ2Answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQ2B)
                                .addComponent(lblQ2D)
                                .addComponent(lblQ2C)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQ2Out, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQ3)
                            .addComponent(txtQ3Answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ3A)
                            .addComponent(lblQ3B)
                            .addComponent(lblQ3D)
                            .addComponent(lblQ3C))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQ3Out, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQ4)
                            .addComponent(txtQ4Answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ4B)
                            .addComponent(lblQ4D)
                            .addComponent(lblQ4C)
                            .addComponent(lblQ4A))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQ4Out, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQ5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQ5Answer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ5Out, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblScore)
                                    .addComponent(lblScoreOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblQ5A)
                                        .addComponent(lblQ5B))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblQ5C)
                                        .addComponent(lblQ5D)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(lblScorePerc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int correct;
        int score;
        int answer;
        int answer2;
        int answer3;
        int answer4;
        int answer5;
        int percentage = 0;
        final int TOTAL_QUESTIONS = 5;
   
        score = 0;
        answer = Integer.parseInt(txtQ1Answer.getText());
        if (answer == 4) { 
        lblQ1Out.setText("Correct!");
        score = score + 1;
        } else if (answer != 4) {
          lblQ1Out.setText("The answer was 4");
        }
        answer2 = Integer.parseInt(txtQ2Answer.getText());
        if (answer2 == 1) {
        lblQ2Out.setText("Correct!");
        score = score + 1;
        } else if (answer2 != 1) {
          lblQ2Out.setText("The answer was 1");
        }
        answer3 = Integer.parseInt(txtQ3Answer.getText());
        if (answer3 == 2) {
        lblQ3Out.setText("Correct!");
        score = score + 1;
        } else if (answer3 != 2) {
          lblQ3Out.setText("The answer was 2");
        }
        answer4 = Integer.parseInt(txtQ4Answer.getText());
        if (answer4 == 3) {
        lblQ4Out.setText("Correct!");
        score = score + 1;
        } else if (answer4 != 3) {
          lblQ4Out.setText("The answer was 3");
        }
        answer5 = Integer.parseInt(txtQ5Answer.getText());
        if (answer5 == 4) {
        lblQ5Out.setText("Correct!");
        score = score + 1;
        } else if (answer5 != 4) {
          lblQ5Out.setText("The answer was 4");
        }
    percentage = (score * 100) / TOTAL_QUESTIONS;
    lblScorePerc.setText("" + percentage + "%");    
    lblScoreOutput.setText("" + score + "/" + TOTAL_QUESTIONS);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtQ1AnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ1AnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ1AnswerActionPerformed

    private void txtQ3AnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ3AnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ3AnswerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiChoiceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Q1BtnGroup;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbQ2;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ1A;
    private javax.swing.JLabel lblQ1B;
    private javax.swing.JLabel lblQ1C;
    private javax.swing.JLabel lblQ1D;
    private javax.swing.JLabel lblQ1Out;
    private javax.swing.JLabel lblQ2A;
    private javax.swing.JLabel lblQ2B;
    private javax.swing.JLabel lblQ2C;
    private javax.swing.JLabel lblQ2D;
    private javax.swing.JLabel lblQ2Out;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ3A;
    private javax.swing.JLabel lblQ3B;
    private javax.swing.JLabel lblQ3C;
    private javax.swing.JLabel lblQ3D;
    private javax.swing.JLabel lblQ3Out;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ4A;
    private javax.swing.JLabel lblQ4B;
    private javax.swing.JLabel lblQ4C;
    private javax.swing.JLabel lblQ4D;
    private javax.swing.JLabel lblQ4Out;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ5A;
    private javax.swing.JLabel lblQ5B;
    private javax.swing.JLabel lblQ5C;
    private javax.swing.JLabel lblQ5D;
    private javax.swing.JLabel lblQ5Out;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreOutput;
    private javax.swing.JLabel lblScorePerc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblimg2;
    private javax.swing.JTextField txtQ1Answer;
    private javax.swing.JTextField txtQ2Answer;
    private javax.swing.JTextField txtQ3Answer;
    private javax.swing.JTextField txtQ4Answer;
    private javax.swing.JTextField txtQ5Answer;
    // End of variables declaration//GEN-END:variables

    }

    

